version: '{build}'
os: Visual Studio 2015
configuration: Release
platform: Any CPU

environment:
  ANDROID_HOME: C:\android-sdk
  AndroidSdkDirectory: C:\android-sdk
  GitHubToken:
    secure: ++Q00Aa+yzbi4oEn+fOuO2D2pb4NrFtQ12Hiq69arY1OgOIIUbth7nlImS9/wQRd
  AppVeyorToken:
    secure: 5mY0TVM+8MUtvl18rZ+eCuXoLMWgxJCpVRTUvry+mG4=
  NoWarn: ;1591;
  ContinueOnDisconnected: False
   
xamarin:
  email: 
    secure: +SUXZSPLHwp39+Yh09d2xxVGsEgHtlSD4NT1Og5h3sg=
  password:
    secure: Tvdf5rZl6IOCwZbvyj9B2w==
  android: true
  ios: true

install:
 - cmd: .\build-scripts\appveyor-before-build.cmd
  
build_script:
 - ps: .\bootstrapper.ps1 -Target Default-Windows -Configuration $Env:Configuration
  
artifacts:
 - path: output
 - path: output\*.nupkg
 - path: output\*.xam
